### ISSUE TITLE
Option to disable jump on highlight selection

### ISSUE THREAD

**Issue by daeh** [spywhere/vscode-mark-jump#28]
When I click the Mark Jump 'sections' icon in the status bar, the current editor scrolls to the first section mark. Is that the intended behavior? I'd prefer it if the scroll location didn't change until a section was selected.

Mark Jump v0.9.0
VS Code v1.47.2
MacOS v10.15.6

**Comment by spywhere** [comment]
Haven't confirm the behaviour, but MarkJump will go to the first location when the section was selected. However, by default, VSCode always select the first section as soon as the popup appears.

**Comment by daeh** [comment]
![markjump](https://user-images.githubusercontent.com/12652166/90069785-c7ac2280-dcc0-11ea-901c-3b11063a8cf8.gif)

Gif of behavior

**Comment by spywhere** [comment]
That's seems to be a correct behaviour to me. Hence this seems like you want it so that upon open a mark list, it would not automatically jumped until you actually choose it.

To clarify a bit more, Mark Jump will automatically jumped when you select the item (but not yet choose it) but if you dismissed the pick list, it will return to the original location.

**Comment by daeh** [comment]
Ok, I guess I'm just used to rstudio's behavior. Thanks!

![rstudio](https://user-images.githubusercontent.com/12652166/90343515-fbe45380-dfde-11ea-998b-935493a63ce3.gif)

**Comment by spywhere** [comment]
Close as it can be done through "Always Open Document" configuration option.
