### ISSUE TITLE
Understanding problems

### ISSUE THREAD

**Issue by AxelGauffre** [spywhere/vscode-mark-jump#29]
Hi,

Thank you for this extension. :-)
It looks very useful.

But I am trying to use your Mark Jum extension, but some settings are not very clear to me.

1- You mention the word "project" a lot, but I don't understant what you mean here?
Are you refering to a workspace? A folder?
What do you mean by "project" ?

2- Since I don't understand the meaning of "project",
I don't understant either the usage of the Exclude File Pattern setting.
Could you explain me what it means and how to use it.

3- Same for Include File Pattern.

4- Same for Show Project Marks.

5- What does the Always Open Documet setting do?
Does it mean that if it is unchecked the document containing the mark won't open when I click on it?

6- Also, How often is the list refreshed?

7-Finally, I don't manage to have, in the Explorer bar the list of the marks that are outside the file I'm currently in...

Can you help

**Comment by spywhere** [comment]
Hi, thanks for checking out!

> 1- You mention the word "project" a lot, but I don't understant what you mean here?
> Are you refering to a workspace? A folder?
> What do you mean by "project" ?

Yes, it's referring to a workspace in this context. The extension is developed prior to a workspace feature on the VSCode, hence it's using the word "project" here.

> 2- Since I don't understand the meaning of "project",
> I don't understant either the usage of the Exclude File Pattern setting.
> Could you explain me what it means and how to use it.
> 
> 3- Same for Include File Pattern.

What Mark Jump does when you want to jump to any particular mark is

1. Look up all the files in the workspace
2. Run through each file, performing a pattern matching and keep records of it
3. Show a list of all marks found

Include/Exclude file pattern is useful when you performing a search on a large project, in which you might want to include/exclude some particular file patterns to help speed up the search by not go through the one that are not relevant.

Feel free to take a look at https://github.com/spywhere/vscode-mark-jump/issues/15 for more details on pattern setup.

> 4- Same for Show Project Marks.

It's simply to show every marks for every files in your workspace, rather than limited to the current file that you're working on.

> 5- What does the Always Open Documet setting do?
> Does it mean that if it is unchecked the document containing the mark won't open when I click on it?

"Always Open Document" means that Mark Jump will open a file and jump to it upon "highlight" the selection. While disable this option, it will jump to the mark only when you actually select it.

> 6- Also, How often is the list refreshed?

Usually, it will update when you do one of the following actions...

- Open a file
- Close a file
- Change configuration options
- Change editor view columns
- Switch file (editor)

> 7-Finally, I don't manage to have, in the Explorer bar the list of the marks that are outside the file I'm currently in...
> 
> Can you help

Both status bar item and explorer item used the same mechanic, which is...

- Showing an editor's marks when you're working on a file
- Showing a workspace's marks when no editor is opened

Hope this should clear out any question that you might have there, feel free to let me know if something is not clear.
